export const ADMIN_ROUTE = '/Sultan-Shop/admin'
export const CATALOG_ROUTE = '/Sultan-Shop/catalog'
export const BASKET_ROUTE = '/Sultan-Shop/basket'
export const PRODUCT_ROUTE = '/Sultan-Shop/catalog/product'
export const MAIN_ROUTE = '/Sultan-Shop/'